# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 20) do

  create_table "account_types", :force => true do |t|
    t.column "name",  :string, :limit => 100
    t.column "title", :string, :limit => 100
  end

  create_table "accounts", :force => true do |t|
    t.column "title",           :string,  :limit => 100
    t.column "client_id",       :integer
    t.column "parent_id",       :integer
    t.column "account_type_id", :integer
    t.column "number",          :integer
  end

  create_table "bookings", :force => true do |t|
    t.column "title",             :string,  :limit => 100
    t.column "amount",            :decimal
    t.column "credit_account_id", :integer
    t.column "debit_account_id",  :integer
    t.column "value_date",        :date
    t.column "comments",          :string,  :limit => 1000, :default => ""
    t.column "scan",              :string
    t.column "debit_currency",    :string,                  :default => "CHF"
    t.column "credit_currency",   :string,                  :default => "CHF"
    t.column "exchange_rate",     :float,                   :default => 1.0
  end

  create_table "clients", :force => true do |t|
    t.column "name", :string, :limit => 100
  end

  create_table "days", :force => true do |t|
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "date",            :date
    t.column "cash",            :float,    :default => 0.0
    t.column "card_turnover",   :float,    :default => 0.0
    t.column "gross_turnover",  :float,    :default => 0.0
    t.column "net_turnover",    :float,    :default => 0.0
    t.column "client_count",    :integer,  :default => 0
    t.column "product_count",   :integer,  :default => 0
    t.column "expenses",        :float,    :default => 0.0
    t.column "credit_turnover", :float,    :default => 0.0
  end

  create_table "products", :force => true do |t|
  end

# Could not dump table "sqlite_sequence" because of following StandardError
#   Unknown type '' for column 'name'

  create_table "vcards", :force => true do |t|
    t.column "full_name",          :string,  :limit => 50
    t.column "nickname",           :string,  :limit => 50
    t.column "address",            :integer
    t.column "billing_address_id", :integer
    t.column "address_id",         :integer
    t.column "family_name",        :string,  :limit => 50
    t.column "given_name",         :string,  :limit => 50
    t.column "additional_name",    :string,  :limit => 50
    t.column "honorific_prefix",   :string,  :limit => 50
    t.column "honorific_suffix",   :string,  :limit => 50
  end

end
